import React, { useState } from "react";
import { Eye, Trash2, SquarePen, Funnel, Plus, Play, Pause, Calendar } from "lucide-react";

const Invoices = () => {
  const [activeTab, setActiveTab] = useState("invoices");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isRecurringModalOpen, setIsRecurringModalOpen] = useState(false);
  const [activeStatus, setActiveStatus] = useState(true);

  // INVOICE DATA
  const invoices = [
    {
      id: "INV-001",
      customer: "John Doe",
      total: "5400.00",
      status: "Paid",
      invoiceDate: "2025-01-15",
      dueDate: "2025-02-15",
      agent: "Agent K",
    },
    {
      id: "INV-002",
      customer: "John Doe",
      total: "5400.00",
      status: "Pending",
      invoiceDate: "2025-01-15",
      dueDate: "2025-02-15",
      agent: "Agent L",
    },
    {
      id: "INV-003",
      customer: "John Doe",
      total: "5400.00",
      status: "Overdue",
      invoiceDate: "2025-01-15",
      dueDate: "2025-02-15",
      agent: "Agent I",
    },
  ];
  // RECURRING SCHEDULES DATA
  const recurringSchedules = [
    {
      template: "INV-001",
      customer: "John Doe",
      period: "Monthly",
      nextRunDate: "2025-02-15",
      status: "Active",
      autoGenerated: "3 invoices",
    },
    {
      template: "INV-005",
      customer: "ABC Corp",
      period: "Weekly",
      nextRunDate: "2025-01-22",
      status: "Active",
      autoGenerated: "12 invoices",
    },
    {
      template: "INV-010",
      customer: "XYZ Ltd",
      period: "Custom (45 days)",
      nextRunDate: "2025-03-01",
      status: "Inactive",
      autoGenerated: "0 invoices",
    },
  ];
  // AUTO-GENERATED DRAFTS DATA
  const draftInvoices = [
    {
      id: "DRAFT-001",
      customer: "John Doe",
      total: "5400.00",
      generatedDate: "2025-01-15",
      dueDate: "2025-02-15",
    },
    {
      id: "DRAFT-002",
      customer: "ABC Corp",
      total: "2100.00",
      generatedDate: "2025-01-15",
      dueDate: "2025-02-15",
    },
  ];

  // LINE ITEMS FOR CREATE INVOICE MODAL
  const [lineItems, setLineItems] = useState([
    { id: Date.now(), product: "", quantity: "", unitPrice: "", tax: "" },
  ]);

  // ADD, REMOVE, UPDATE LINE ITEMS
  const addLineItem = () => {
    setLineItems((prev) => [
      ...prev,
      { id: Date.now(), product: "", quantity: "", unitPrice: "", tax: "" },
    ]);
  };
  const removeLineItem = (id) => {
    if (lineItems.length === 1) return;
    setLineItems((prev) => prev.filter((item) => item.id !== id));
  };
  const updateLineItem = (id, field, value) => {
    setLineItems((prev) =>
      prev.map((item) => (item.id === id ? { ...item, [field]: value } : item))
    );
  };

  // CALCULATE TOTALS
  const subtotal = lineItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.unitPrice) || 0),
    0
  );
  const totalTax = lineItems.reduce(
    (sum, item) => sum + (parseFloat(item.tax) || 0),
    0
  );
  const grandTotal = subtotal + totalTax;

  // STATUS COLOR - INVOICE
  const getStatusColor = (status) => {
    if (status === "Paid") return "bg-green-100 text-green-800";
    if (status === "Pending") return "bg-yellow-100 text-yellow-800";
    if (status === "Overdue") return "bg-red-100 text-red-800";
    return "bg-gray-100 text-gray-800";
  };

  // STATUS COLOR - RECURRING
  const getRecurringStatusColor = (status) =>
    status === "Active"
      ? "bg-green-100 text-green-800"
      : "bg-gray-100 text-gray-600";

  return (
    <div className="min-h-screen bg-gray-50">
      {/* MAIN CONTAINER */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200">
          {/* HEADER */}
          <div className="px-6 py-4 border-b border-gray-200">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              {/* TABS */}
              <div className="flex space-x-1 bg-gray-100 p-1 rounded-2xl">
                <button
                  onClick={() => setActiveTab("invoices")}
                  className={`px-5 py-2 text-sm font-medium rounded-2xl transition-all ${
                    activeTab === "invoices"
                      ? "bg-white text-gray-800 shadow-sm"
                      : "text-gray-700 hover:bg-gray-200 hover:cursor-pointer"
                  }`}
                >
                  Invoices
                </button>
                <button
                  onClick={() => setActiveTab("recurring")}
                  className={`px-5 py-2 text-sm font-medium rounded-2xl transition-all ${
                    activeTab === "recurring"
                      ? "bg-white text-gray-800 shadow-sm"
                      : "text-gray-700 hover:bg-gray-200 hover:cursor-pointer"
                  }`}
                >
                  Recurring Invoices
                </button>
              </div>

              {/* ACTION BUTTONS */}
              <div className="flex items-center space-x-3">
                <button className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-800 bg-white border border-gray-400 rounded-lg hover:bg-gray-700 hover:text-white transition-colors hover:cursor-pointer">
                  <Funnel className="w-4 h-4" />
                  Filter
                </button>

                {activeTab === "invoices" ? (
                  <button
                    onClick={() => setIsModalOpen(true)}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-[#660033] bg-white border border-[#660033] rounded-lg hover:bg-[#660033] hover:text-white transition-colors hover:cursor-pointer"
                  >
                    <Plus className="w-4 h-4" />
                    Create Invoice
                  </button>
                ) : (
                  <button
                    onClick={() => setIsRecurringModalOpen(true)}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-[#660033] bg-white border border-[#660033] rounded-lg hover:bg-[#660033] hover:text-white transition-colors hover:cursor-pointer"
                  >
                    <Plus className="w-4 h-4" />
                    Create Recurring Schedule
                  </button>
                )}
              </div>
            </div>
          </div>

          {/* INVOICE TAB */}
          {activeTab === "invoices" && (
            <>
              <div className="px-6 py-5">
                <h2 className="text-xl font-semibold text-gray-900">Invoice List</h2>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="text-left text-xs font-medium text-gray-500 uppercase tracking-wider bg-gray-50">
                      <th className="px-6 py-4">Invoice #</th>
                      <th className="px-6 py-4">Customer</th>
                      <th className="px-6 py-4">Total (RM)</th>
                      <th className="px-6 py-4">Status</th>
                      <th className="px-6 py-4">Invoice Date</th>
                      <th className="px-6 py-4">Due Date</th>
                      <th className="px-6 py-4">Sales Agent</th>
                      <th className="px-6 py-4"></th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {invoices.map((invoice) => (
                      <tr key={invoice.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 text-sm text-gray-900 font-medium cursor-pointer hover:text-[#660033]">
                          {invoice.id}
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-800">{invoice.customer}</td>
                        <td className="px-6 py-4 text-sm text-gray-800">{invoice.total}</td>
                        <td className="px-6 py-4">
                          <span
                            className={`inline-flex justify-center px-3 py-1 text-xs font-semibold rounded-full w-24 ${getStatusColor(
                              invoice.status
                            )}`}
                          >
                            {invoice.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-800">{invoice.invoiceDate}</td>
                        <td className="px-6 py-4 text-sm text-gray-800">{invoice.dueDate}</td>
                        <td className="px-6 py-4 text-sm text-gray-800">{invoice.agent}</td>
                        <td className="px-6 py-4">
                          <div className="flex items-center justify-end gap-4">
                            <button className="text-gray-600 hover:text-gray-900 hover:cursor-pointer">
                              <Eye className="w-4 h-4" />
                            </button>
                            <button className="text-gray-600 hover:text-gray-900 hover:cursor-pointer">
                              <SquarePen className="w-4 h-4" />
                            </button>
                            <button className="text-red-600 hover:text-red-800 hover:cursor-pointer">
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </>
          )}

          {/* RECURRING INVOICE TAB */}
          {activeTab === "recurring" && (
            <div className="p-6 space-y-10">
              {/* RECURRING SCHEDULES */}
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-4">
                  Recurring Invoice Schedules
                </h3>
                <div className="border border-gray-200 rounded-lg overflow-hidden">
                  <table className="w-full">
                    <thead className="bg-gray-50">
                      <tr className="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        <th className="px-6 py-3">Invoice Template</th>
                        <th className="px-6 py-3">Customer</th>
                        <th className="px-6 py-3">Period</th>
                        <th className="px-6 py-3">Next Run Date</th>
                        <th className="px-6 py-3">Status</th>
                        <th className="px-6 py-3">Auto-Generated</th>
                        <th className="px-6 py-3">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {recurringSchedules.map((sched) => (
                        <tr key={sched.template} className="hover:bg-gray-50">
                          <td className="px-6 py-4 text-sm font-medium text-[#660033] cursor-pointer">
                            {sched.template}
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-800">{sched.customer}</td>
                          <td className="px-6 py-4 text-sm text-gray-800">{sched.period}</td>
                          <td className="px-6 py-4 text-sm text-gray-800">{sched.nextRunDate}</td>
                          <td className="px-6 py-4">
                            <span
                              className={`inline-flex justify-center gap-1.5 px-3 py-1 text-xs font-semibold rounded-full w-25 ${getRecurringStatusColor(
                                sched.status
                              )}`}
                            >
                              {sched.status === "Active" ? (
                                <Play className="w-3.5 h-3.5" />
                              ) : (
                                <Pause className="w-3.5 h-3.5" />
                              )}
                              {sched.status}
                            </span>
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-600">
                            {sched.autoGenerated}
                          </td>
                          <td className="px-6 py-4">
                            <div className="flex items-center gap-4">
                              <button className="text-gray-600 hover:text-gray-900 hover:cursor-pointer">
                                <Pause className="w-4 h-4" />
                              </button>
                              <button className="text-gray-600 hover:text-gray-900 hover:cursor-pointer">
                                <Play className="w-4 h-4" />
                              </button>
                              <button className="text-gray-600 hover:text-gray-900 hover:cursor-pointer">
                                <Calendar className="w-4 h-4" />
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* AUTO-GENERATED DRAFTS */}
              <div>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-gray-900">
                    Auto Generated Invoice Drafts
                  </h3>
                  <button className="px-4 py-2 text-sm font-medium text-[#660033] bg-white border border-[#660033] rounded-lg hover:bg-[#660033] hover:text-white transition-colors hover:cursor-pointer">
                    Batch Submit All ({draftInvoices.length})
                  </button>
                </div>

                <div className="border border-gray-200 rounded-lg overflow-hidden">
                  <table className="w-full">
                    <thead className="bg-gray-50">
                      <tr className="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        <th className="px-6 py-3">Draft #</th>
                        <th className="px-6 py-3">Customer</th>
                        <th className="px-6 py-3">Total (RM)</th>
                        <th className="px-6 py-3">Generated Date</th>
                        <th className="px-6 py-3">Due Date</th>
                        <th className="px-6 py-3">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {draftInvoices.map((draft) => (
                        <tr key={draft.id} className="hover:bg-gray-50">
                          <td className="px-6 py-4 text-sm font-medium text-[#660033] cursor-pointer">
                            {draft.id}
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-800">{draft.customer}</td>
                          <td className="px-6 py-4 text-sm text-gray-800">{draft.total}</td>
                          <td className="px-6 py-4 text-sm text-gray-800">{draft.generatedDate}</td>
                          <td className="px-6 py-4 text-sm text-gray-800">{draft.dueDate}</td>
                          <td className="px-6 py-4">
                            <div className="flex items-center gap-4">
                              <button className="text-sm px-5 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 hover:cursor-pointer">
                                Review
                              </button>
                              <button className="text-sm px-5 py-2 bg-[#660033] text-white rounded-md hover:bg-[#4f0026] hover:cursor-pointer">
                                Approve
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ====================== CREATE INVOICE MODAL ====================== */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/10">
          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-4xl max-h-[92vh] overflow-y-auto">
            {/* HEADER */}
            <div className="flex items-center justify-between px-8 py-5 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">Create New Invoice</h3>
            </div>

            {/* BODY */}
            <div className="p-8 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Invoice Number <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. INV-2025-001"
                    className="w-full px-4 py-2 border border-gray-300 rounded-md"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Invoice Date <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="date"
                    className="w-full px-4 py-2 border border-gray-300 rounded-md"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Due Date <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="date"
                    className="w-full px-4 py-2 border border-gray-300 rounded-md"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Customer <span className="text-red-500">*</span>
                  </label>
                  <select className="w-full px-4 py-2 border border-gray-300 rounded-md">
                    <option>Select customer</option>
                    <option>John Doe</option>
                    <option>ABC Corp</option>
                    <option>XYZ Ltd</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Customer Reference (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="PO12345"
                    className="w-full px-4 py-2 border border-gray-300 rounded-md"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Sales Agent (Optional)
                </label>
                <select className="w-full px-4 py-2 border border-gray-300 rounded-md">
                  <option>Select agent</option>
                  <option>Agent K</option>
                  <option>Agent L</option>
                </select>
              </div>

              {/* ADD ITEMS */}
              <div>
                <h4 className="text-lg font-semibold text-gray-800 mb-4">
                  Product Line Items
                </h4>
                <div className="border border-gray-300 rounded-lg overflow-hidden">
                  <table className="w-full">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-800 uppercase">Product</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-800 uppercase">Quantity</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-800 uppercase">Unit Price</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-800 uppercase">Tax</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-800 uppercase">Total</th>
                        <th className="w-12"></th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                      {lineItems.map((item) => (
                        <tr key={item.id}>
                          <td className="px-4 py-3">
                            <select
                              value={item.product}
                              onChange={(e) => updateLineItem(item.id, "product", e.target.value)}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
                            >
                              <option value="">Select product</option>
                              <option>Web Design Service</option>
                              <option>Logo Design</option>
                              <option>Hosting Plan</option>
                            </select>
                          </td>
                          <td className="px-4 py-3">
                            <input
                              type="number"
                              min="0"
                              placeholder="0"
                              value={item.quantity}
                              onChange={(e) => updateLineItem(item.id, "quantity", e.target.value)}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
                            />
                          </td>
                          <td className="px-4 py-3">
                            <input
                              type="number"
                              step="0.01"
                              placeholder="0.00"
                              value={item.unitPrice}
                              onChange={(e) => updateLineItem(item.id, "unitPrice", e.target.value)}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
                            />
                          </td>
                          <td className="px-4 py-3">
                            <input
                              type="number"
                              step="0.01"
                              placeholder="0.00"
                              value={item.tax}
                              onChange={(e) => updateLineItem(item.id, "tax", e.target.value)}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
                            />
                          </td>
                          <td className="px-4 py-3 text-right font-medium">
                            {(
                              (parseFloat(item.quantity) || 0) *
                                (parseFloat(item.unitPrice) || 0) +
                              (parseFloat(item.tax) || 0)
                            ).toFixed(2)}
                          </td>
                          <td className="px-4 py-3 text-center">
                            <button
                              onClick={() => removeLineItem(item.id)}
                              disabled={lineItems.length === 1}
                              className="text-red-600 hover:text-red-800 disabled:opacity-30 hover:cursor-pointer"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <button
                  onClick={addLineItem}
                  className="mt-4 flex items-center text-[#660033] text-sm font-medium hover:underline hover:cursor-pointer"
                >
                  <Plus className="w-4 h-4 mr-1" />
                  Add Item
                </button>
              </div>

              {/* SUMMARY */}
              <div className="max-w-xs ml-auto space-y-2 bg-gray-50 p-4 rounded-lg">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Subtotal:</span>
                  <span className="font-medium">RM {subtotal.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Tax:</span>
                  <span className="font-medium">RM {totalTax.toFixed(2)}</span>
                </div>
                <div className="flex justify-between pt-3 border-t border-gray-300 text-lg font-bold text-gray-900">
                  <span>Total Amount:</span>
                  <span>RM {grandTotal.toFixed(2)}</span>
                </div>
              </div>
            </div>

            {/* FOOTER */}
            <div className="flex justify-end gap-3 px-8 py-5 border-t border-gray-200">
              <button
                onClick={() => setIsModalOpen(false)}
                className="px-6 py-2.5 text-sm font-medium text-[#660033] bg-white border border-[#660033] rounded-lg hover:cursor-pointer"
              >
                Cancel
              </button>
              <button className="px-6 py-2.5 text-sm font-medium text-[#660033] bg-white border border-[#660033] rounded-lg hover:cursor-pointer">
                Save As Draft
              </button>
              <button className="px-6 py-2.5 text-sm font-medium text-white bg-[#660033] rounded-lg hover:cursor-pointer">
                Submit
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ================= CREATE RECURRING SCHEDULE MODAL ================= */}
      {isRecurringModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/10">
          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-lg p-8 space-y-4">

            {/* HEADER */}
            <h2 className="text-xl font-semibold text-gray-800">
              Create Recurring Invoice Schedule
            </h2>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Select Invoice</label>
              <input
                type="text"
                className="w-full px-4 py-2 border border-gray-300 rounded-md"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Time Period <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                placeholder=""
                className="w-full px-4 py-2 border border-gray-300 rounded-md"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Custom Days (if applicable)</label>
              <input
                type="text"
                placeholder=""
                className="w-full px-4 py-2 border border-gray-300 rounded-md"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Next Run Date *</label>

              <div className="relative mt-1">
                <input
                  type="date"
                  className="w-full px-4 py-2 border border-gray-300 rounded-md"
                />
              </div>
            </div>
            <div className="flex items-center gap-3 pt-2">
              <label className="text-sm font-medium text-gray-700">Active Status</label>
              <label className="relative inline-flex items-center cursor-pointer">
                <input
                  type="checkbox"
                  className="sr-only peer"
                  checked={activeStatus}
                  onChange={() => setActiveStatus(!activeStatus)}
                />
                <div className="w-11 h-6 bg-gray-300 rounded-full peer peer-checked:bg-[#660033] transition-colors duration-300"></div>
                <div className="absolute left-1 top-1 w-4 h-4 bg-white rounded-full transition-transform duration-300 peer-checked:translate-x-5"></div>
              </label>
            </div>

            {/* FOOTER BUTTONS */}
            <div className="flex justify-end gap-3 pt-4">
              <button
                onClick={() => setIsRecurringModalOpen(false)}
                className="px-6 py-2 text-sm font-medium text-[#660033] border border-[#660033] rounded-lg hover:bg-gray-50 hover:cursor-pointer">
                Cancel
              </button>

              <button className="px-6 py-2 text-sm font-medium text-white bg-[#660033] rounded-lg hover:bg-[#4f0026] hover:cursor-pointer">
                Create Schedule
              </button>
            </div>

          </div>
        </div>
      )}
    </div>
  );
};

export default Invoices;